services:
  db:
    image: postgres:15-alpine
    container_name: rivulet_postgres
    restart: always
    environment:
      POSTGRES_USER: rivulet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rivulet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
