services:
  backend:
    build: .
    container_name: rivulet_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_DSN=host=db user=rivulet password=password dbname=rivulet_db port=5432 sslmode=disable TimeZone=UTC
      - JWT_SECRET=your_production_secret_key
    volumes:
      - ../data/assets:/app/assets
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: rivulet_postgres
    restart: always
    environment:
      POSTGRES_USER: rivulet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rivulet_db
    ports:
      - "5432:5432"
    volumes:
      - ../data/db:/var/lib/postgresql/data